In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:

# 做一个方腔流
Nx   = 100
Ny   = 100
rho0 = 100 # 为什么平均密度是100
tau  = 0.6 # 松弛时间
Nt   = 10000 # 迭代次数

plotRealTime = True

#Lattice speeds / weights
NL = 9

F = np.zeros((Nx, Ny, NL)) # 速度分布函数

rho0 = 1 #初始密度
u0 = 0.1 #初始速度

niu = 0.01 #

Re = u0*Ny/niu #雷诺数

Ntstep = 1e4

w = np.array([4/9] + [1/9]*4 + [1/36]*4) #权重
cx = np.array([0, 1, 0, -1, 0, 1, -1, -1, 1]) #速度分量
cy = np.array([0, 0, 1, 0, -1, 1, 1, -1, -1]) #速度分量

rho = np.ones((Nx, Ny)) * rho0 #密度分布函数

u = np.zeros((Nx, Ny)) #x 上的速度分布函数
v = np.zeros((Nx, Ny)) #y 上的速度分布函数


u[:,Nx] = u0 #初始速度分布函数
u[0,0] = 0 # 这一步会影响吗

omega = 1/(3*tau + 0.5) #松弛时间

cs  = 1/np.sqrt(3) #声速
cs2 = cs**2 #声速平方
for t in range(Ntstep): 

    # 先进行碰撞
    for i in range(NL):
        cu = (cx[i]*u + cy[i]*v) #速度分布函数
        feq = rho * w[i] * (1 + cu/cs2 + cu**2/(2*cs2^2) - (u**2 + v**2)/(2*cs2) ) #平衡分布函数
        F[:,:,i] = (1 - omega) * F[:,:,i] + (omega) * feq #碰撞


    # 进行迁移
    # 联系迁移和边界条件反射同时理解
    F = Streaming(F) #迁移函数

    # 进行边界条件处理


In [ ]:
def Streaming( F ,NL,cx,cy) -> np.ndarray:
    # 尝试写一个笨拙的迁移操作
    # 要额外处理边界的部分
    for i in range(NL):
        F[1:,:,1]     = F[0:-1:1,:,1] # 没有对边界进行额外处理
        F[:,1:, 2]    = F[:,0:-1:1,2]  
        F[0:-1:1,:,3] = F[1:,:,3] 
        F[:,0:-1:1,4] = F[:,1:,4]
        F[1:,1:,5]    = F[0:-1: ,0:-1 ,5]
        F[:,:, 6] = F[:,:,6]
        F[0:-1:1,:,7] = F[1:,:,7]
        F[:,:, 8] = F[:,:,8]


    return F
def BoundaryCondition(F, NL):
    # 处理边界条件
    
    F[0,:,1] = F[0,:,3]    
    F[0,:,5] = F[0,:,7] 
    F[0,:,8] = F[0,:,6]

    F[-1,:,3] = F[-1,:,1] 
    F[-1,:,7] = F[-1,:,5]
    F[-1,:,6] = F[-1,:,8]

    F[:,0,2] = F[:,0,4]
    F[:,0,5] = F[:,0,7]
    F[:,0,6] = F[:,0,8]

    # slide 边界条件
    rhon = F[ 1:-1:1, -1, 0]  + F[ 1:-1:1 ,-1 ,1] + 

    return F




array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 2,  2,  2, ...,  2,  2,  2],
       ...,
       [97, 97, 97, ..., 97, 97, 97],
       [98, 98, 98, ..., 98, 98, 98],
       [99, 99, 99, ..., 99, 99, 99]])

In [10]:
np.size(F)

360000

In [13]:
T=F[:,:,3]

In [21]:
X**2

array([[     0,      1,      4, ..., 157609, 158404, 159201],
       [     0,      1,      4, ..., 157609, 158404, 159201],
       [     0,      1,      4, ..., 157609, 158404, 159201],
       ...,
       [     0,      1,      4, ..., 157609, 158404, 159201],
       [     0,      1,      4, ..., 157609, 158404, 159201],
       [     0,      1,      4, ..., 157609, 158404, 159201]])

In [25]:
Y[1,100]

1

In [26]:

w = np.array([4/9] + [1/9]*4 + [1/36]*4)

In [27]:
w

array([0.44444444, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
       0.02777778, 0.02777778, 0.02777778, 0.02777778])

In [28]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [37]:
A[:,0:-1:1]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [41]:
A[:,1::1]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])