In [1]:
import numpy as np

# 定义一维坐标
x = np.linspace(0, 1, 5)   # [0.   0.25 0.5  0.75 1.  ]
y = np.linspace(0, 2, 3)   # [0. 1. 2. ]

# 默认 indexing='xy'
X, Y = np.meshgrid(x, y)
print(X.shape, Y.shape)
# (3, 5) (3, 5)

print("X =\n", X)
# [[0.   0.25 0.5  0.75 1.  ]
#  [0.   0.25 0.5  0.75 1.  ]
#  [0.   0.25 0.5  0.75 1.  ]]

print("Y =\n", Y)
# [[0. 0. 0. 0. 0. ]
#  [1. 1. 1. 1. 1. ]
#  [2. 2. 2. 2. 2. ]]


# 如果想要矩阵索引风格，使用 indexing='ij'
Xi, Yi = np.meshgrid(x, y, indexing='ij')
print(Xi.shape, Yi.shape)
# (5, 3) (5, 3)


(3, 5) (3, 5)
X =
 [[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
Y =
 [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]]
(5, 3) (5, 3)
